docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v5
  versions:
    - v5
    - v4
    - v3
nav:
  - Home: index.md
  - v5:
      - Overview: v5/overview.md
      - Installation: v5/installation.md
      - Configuration: v5/configuration.md
      - "Log files": v5/log-files.md
      - "Extra data":
          - Introduction: v5/extra/introduction.md
          - Cookie: v5/extra/cookie.md
          - Header: v5/extra/header.md
          - Request: v5/extra/request.md
          - Server: v5/extra/server.md
          - Session: v5/extra/session.md
          - "Trace route": v5/extra/trace.md
  - v4:
      - Overview: v4/overview.md
      - Installation: v4/installation.md
      - Configuration: v4/configuration.md
      - "Log files": v4/log-files.md
      - "Extra data":
          - Introduction: v4/extra/introduction.md
          - Cookie: v4/extra/cookie.md
          - Header: v4/extra/header.md
          - Request: v4/extra/request.md
          - Server: v4/extra/server.md
          - Session: v4/extra/session.md
          - "Trace route": v4/extra/trace.md
  - v3:
      - Overview: v3/overview.md
      - Installation: v3/installation.md
      - Configuration: v3/configuration.md
site_name: dot-errorhandler
site_description: "Dotkernel's PSR-15 compliant error handler"
repo_url: "https://github.com/dotkernel/dot-errorhandler"
plugins:
  - search
